/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Skeleton(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/newSkel.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.m_Skeleton.geometry} material={materials.Skeleton} />
        <mesh geometry={nodes.m_Skeleton_1.geometry} material={materials.Skeleton_NoNames} />
      </group>
    </group>
  )
}

useGLTF.preload('/skelton.glb')
